# metaL syntax samples and system startup data

'Dmitry Ponyatov'                   `AUTHOR =
dponyatov@gmail.com                 `EMAIL  =
https://github.com/ponyatov/EDS     `GITHUB =

# line comment

-01 +02.30 -4e+5 0xDeadBeef 0b1101  # numbers

# Web interface

127.0.0.1               `IP     =
12345           port    `PORT   =
`black          color   `BACK   =
`lightgreen     color   `COLOR  =
`monospace      Font    `FONT   =
`4.5mm                  `SIZE   =
rubic.png               `LOGO   =
                                    WEB
